---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

There are certain things -a spider, a ghost  
The income-tax, gout, an umbrella for three -  
That I hate, but the thing that I hate the most  
Is a thing they call the SEA  
Pour some salt water over the floor  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I had for my winter evening walk—  
No one at all with whom to talk,  
But I had the cottages in a row  
Up to their shining eyes in snow.  
And I thought I had the folk within:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

A warrior of the Holy Ones, my tabernacle on mother earth drifting dies  
But, on painted horse run rising up, a brazen spirit storm comes alive  
Free amidst the gale, thunderous beats in temporal instrumental
As clouds begin to blacken, past native spirits dance ceremonial into tornado  
Hozoji drums beating round and round, whirlwind roar of nightly chants  
I, Navajo dreamer stampeding across the azure plains of my once pure native land  
Recompense only to scourge prejudice away and humble the most of evil men  
And then stillness, a silent healing song, as forgiveness is a welcome friend  
